export enum EAnswerType {
  SELECTION = 'SELECTION',
  SELECTION_SHUFFLE = 'SELECTION_SHUFFLE',
  SELECTION_ORDER = 'SELECTION_ORDER',
  TEXT = 'TEXT',
  TEXT_SHUFFLE = 'TEXT_SHUFFLE',
  TEXT_ORDER = 'TEXT_ORDER',
  OTHERS = 'OTHERS',
}
